### ISSUE TITLE
can't build bdist_wheel for 0.4.14

### ISSUE THREAD

**Issue by edmondsw** [python-greenlet/greenlet#136]
Running this command with the newly-released 0.4.14 version on an ppc64le Ubuntu 16.04 system:

`/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-oozK0O/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-tQBkp3 --python-tag cp27`

yields the following error:

```running bdist_wheel
running build
running build_ext
building 'greenlet' extension
creating build
creating build/temp.linux-ppc64le-2.7
powerpc64le-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-ppc64le-2.7/greenlet.o -fno-tree-dominator-opts
In file included from slp_platformselect.h:16:0,
                    from greenlet.c:343:
   platform/switch_ppc64_linux.h: In function 'slp_switch':
   platform/switch_ppc64_linux.h:80:5: error: PIC register clobbered by 'r30' in 'asm'
        __asm__ volatile ("" : : : REGS_TO_SAVE);
        ^
   platform/switch_ppc64_linux.h:95:5: error: PIC register clobbered by 'r30' in 'asm'
        __asm__ volatile ("" : : : REGS_TO_SAVE);
        ^
   error: command 'powerpc64le-linux-gnu-gcc' failed with exit status 1```

**Comment by snaury** [comment]
I was told in #130 this is a gcc bug, which was fixed in https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=9213244550335bcb2b8590a0d7d58ac74c932361

**Comment by edmondsw** [comment]
Thanks, snaury. But the latest gcc available for Ubuntu 16.04 LTS is 5.4.0, which does not have the commit referenced above.

Also, it seems to me that #130 most likely caused this. We were not seeing an issue until today, i.e. immediately after 0.4.14 released (the first release with #130).

**Comment by snaury** [comment]
I would suggest filing a bug report with Ubuntu, or could you maybe switch to official packages instead of building from source? I can't revert the patch, according to ABI it's callee saved, not doing so might cause some weird side-effects/crashes when switching.

**Comment by prometheanfire** [comment]
talking to internal gentoo people they also suggested fixing the actual gcc issue as the proper fix.

**Comment by edmondsw** [comment]
I'm not at all convinced that this is a gcc bug. I am seeing the same issue after setting up "Toolchain test builds" PPA (https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test) to get access to newer versions of gcc. I upgraded gcc-5 and still see the same issue (expected). I then installed gcc-6, gcc-7, and gcc-8 one at a time and tried with each. Same issue. If this is a gcc bug, it doesn't appear to have been fixed yet... i.e. it's not the gcc bug referenced above.

**Comment by edmondsw** [comment]
I found that powerpc64le-linux-gnu-gcc was a symlink still pointing to gcc-5, so installing gcc-7 didn't mean I was actually using it. I updated the symlinks to use gcc-7 and the problem went away. So this does appear to be resolved with the change that went into gcc-7.

**Comment by wiggin15** [comment]
FYI, this is not just about Ubuntu 16.04.
All RedHat-based distributions (RHEL/CentOS/Oracle Linux), including the latest, come with gcc 4.x (see https://access.redhat.com/solutions/19458). This also applies for more distributions like older (but still supported) versions of SLES. _And_ Ubuntu.
We can't always upgrade gcc to a non-default version (we don't always have root access on all of our systems), so we can't install greenlet 0.4.14 on any of these operating systems.

This is a regression from 0.4.13 and prevents us from using the latest version (I see OpenStack already blacklisted this version; unfortunately we are now doing the same)

**Comment by snaury** [comment]
I can't just revert that patch, because then it would become a regression on newer gcc versions. It's probably possible to switch to manual save/load for this register, maybe as simple as something like this:

```
void * r30;
...
__asm__ volatile ("std 30, %0" : "=m" (r30));
...
__asm__ volatile ("ld 30, %0" : : "m" (r30));
...
```

This is already being done for `r2`, so it's probably possible to do for `r30`, which would probably mean it would be safe to remove `r30` from `REGS_TO_SAVE`.

Since I don't have access to the platform I cannot test this and cannot make a PR myself. Anyone with access to and familiar with the platform is welcome to make a PR, making sure it actually compiles and works.

**Comment by snaury** [comment]
Thank you @wiggin15 ! I'll try to make a new 0.4.15 release at the end of the week (probably friday).
